vim.keymap.set('n', 'nt', '<cmd>NvimTreeToggle<cr>')
vim.keymap.set('n', 'nto', '<cmd>NvimTreeOpen<cr>')
vim.keymap.set('n', 'ntc', '<cmd>NvimTreeClose<cr>')
vim.keymap.set('t', 'jj', '<C-\\><C-n>')
vim.keymap.set({'i', }, 'jj', '<Esc>')
